version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - pwd  # Debug: print working directory
            - ls -la  # Debug: show directory contents
            - cd frontend
            - npm install
        build:
          commands:
            - echo "No separate build step needed for Express app"
      artifacts:
        baseDirectory: frontend
        files:
          - '**/*'
    appRoot: .
    env:
      variables:
        NODE_ENV: production
        PORT: 8080 