version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cd frontend
            - npm install
        build:
          commands:
            - echo "No separate build step needed for Express app"
      artifacts:
        baseDirectory: frontend
        files:
          - '**/*'
    appRoot: frontend
    env:
      variables:
        NODE_ENV: production
        PORT: 8080 